version: '3'
services:
  myapp-main:
    image: jkells/springapi2:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/SPRING2FINAL
      - spring.datasource.password=jordan1234
      - spring.datasource.username=root
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver